spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biometry?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:DeepWater@2021}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  config:
    import: "optional:configserver:"

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.esphere: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
