server:
  port: 8089

spring:
  flyway:
    table: flyway_history_reporting

services:
  notification-url: http://localhost:8088
  adherent-url: http://localhost:8082
  prestataire-url: http://localhost:8083
