spring:
  cloud:
    config:
      server:
        # Mode natif : lit les fichiers du dossier config-repo local
        native:
          search-locations: classpath:/config-repo
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/ESPHEREAPI/ERP-APIESPHERE.git}
          default-label: main
          clone-on-start: true
          force-pull: true
    compatibility-verifier:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.esphere: DEBUG
