#Global conf#Global configuration
spring.application.name=sms-Api
#Tomcat configuration
 server.port=9999
 #Log level configuration
 logging.level.root=ERROR
 logging.level.webapi=INFO
 logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# ===============================
# DATABASE
# ===============================
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name= com.mysql.jdbc.Driver
spring.datasource.Url=jdbc:mysql://127.0.0.1:3306/sms_boost?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
spring.datasource.username=root
spring.datasource.password=DeepWater@2021

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

#
#proprety
#
sms.api.hostname=https://smsvas.com/bulk/public/index.php/api/v1/sendsms?
sms.api.expirations=https://zenbio.zenitheinsurance.com:9002/orass/vue-expirations
sms.api.expirations30=https://zenbio.zenitheinsurance.com:9002/orass/vue-expirations30
sms.api.expirations04=https://zenbio.zenitheinsurance.com:9002/orass/vue-expirations04
sms.api.sms_production=https://zenbio.zenitheinsurance.com:9002/orass/vue-sms-production
sms.api.serveSms=https://smsvas.com/bulk/public/index.php/api/v1/sendsms?
sms.api.user=info@zenitheinsurance.com
sms.api.password=biometrie2023
sms.api.senderid=ZENITHE
sms.api.temoin1=+237694923568
sms.api.temoin2=+237674032771
#server.ssl.enabled=true
#security.require-ssl=true
#server.ssl.key-store= keystore.p12
#server.ssl.key-store-password= zenithe
#server.ssl.keyStoreType= PKCS12