-- ============================================
-- SEQUENCES
-- ============================================
CREATE SEQUENCE SEQ_CATEGORIE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CIVILITE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DUREE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ENERGIE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GARANTIE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GENRE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_POLICE_POOLTPV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================
-- TABLES SIMPLES (code + libelle)
-- ============================================
CREATE TABLE POOLTPV_CATEGORIE (
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_CATEGORIE PRIMARY KEY (ID)
);

CREATE TABLE POOLTPV_CIVILITE (
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_CIVILITE PRIMARY KEY (ID)
);

CREATE TABLE POOLTPV_DUREE (
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_DUREE PRIMARY KEY (ID)
);

CREATE TABLE POOLTPV_ENERGIE(
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_ENERGIE PRIMARY KEY (ID)
);

CREATE TABLE POOLTPV_GARANTIE (
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_GARANTIE PRIMARY KEY (ID)
);

CREATE TABLE POOLTPV_GENRE (
    ID      NUMBER(19,0) NOT NULL,
    CODE    VARCHAR2(255),
    LIBELLE VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_GENRE PRIMARY KEY (ID)
);

-- ============================================
-- TABLE POLICE_POOLTPV
-- ============================================
CREATE TABLE POOLTPV_POLICE (
    ID                  NUMBER(19,0) NOT NULL,
    CODE_COMPAGNIE      NUMBER(10,0),
    CODE_INTERMEDIAIRE  NUMBER(10,0),
    NUM_POLICE          VARCHAR2(255) UNIQUE,
    CODE_CATEGORIE      VARCHAR2(255),
    FLOTTE              VARCHAR2(255),
    NOMBRE_VEHICULE     NUMBER(10,0),
    CODE_MOUVEMENT      VARCHAR2(255),
    AVENANT             VARCHAR2(255),
    NUM_AVENANT         VARCHAR2(255),
    DATE_EMISSION       DATE,
    DATE_EFFET          DATE,
    DATE_EXPIRATION     DATE,
    CODE_DUREE          VARCHAR2(255),
    CODE_ASSURE         VARCHAR2(255),
    NOM_ASSURE          VARCHAR2(255),
    PRENOM_ASSURE       VARCHAR2(255),
    ADRESSE_ASSURE      VARCHAR2(255),
    CODE_PROFESSION     VARCHAR2(255),
    GENRE_ASSURE        VARCHAR2(255),
    NUMERO_QUITTANCE    VARCHAR2(255),
    PRIME_NETTE         NUMBER(19,2),
    ACCESSOIRE          NUMBER(19,2),
    TVA                 NUMBER(19,2),
    FC                  NUMBER(19,2),
    CARTE_ROSE          NUMBER(19,2),
    DROIT_TIMBRE        NUMBER(19,2),
    PRIME_TTC           NUMBER(19,2),
    ETAT_ENCAISSEMENT   VARCHAR2(255),
    MODE_ENCAISSEMENT   VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_POLICE PRIMARY KEY (ID)
);

-- ============================================
-- TABLE RISQUE_POOLTPV (ID = VARCHAR)
-- ============================================
CREATE TABLE POOLTPV_RISQUE (
    ID                  VARCHAR2(255) NOT NULL,
    CODE_COMPAGNIE      NUMBER(10,0),
    CODE_INTERMEDIAIRE  NUMBER(10,0),
    NUM_POLICE          VARCHAR2(255),
    FLOTTE              VARCHAR2(255),
    CODE_MOUVEMENT      VARCHAR2(255),
    AVENANT             VARCHAR2(255),
    NUM_AVENANT         VARCHAR2(255),
    DATE_EMISSION       DATE,
    HEURE_EMISSION      VARCHAR2(255),
    DATE_EFFET          DATE,
    DATE_EXPIRATION     DATE,
    CODE_DUREE          VARCHAR2(255),
    DUREE               VARCHAR2(255),
    USAGE               VARCHAR2(255),
    IMMATRICULATION     VARCHAR2(255),
    PUISSANCE           NUMBER(10,0),
    CODE_GENRE_AUTO     VARCHAR2(255),
    GENRE_AUTO          VARCHAR2(255),
    LIBELLE_MARQUE      VARCHAR2(255),
    TYPE_VEH            VARCHAR2(255),
    NBRE_PLACES         NUMBER(10,0),
    DATE_MC             DATE,
    POIDS_VIDE          NUMBER(19,2),
    VALEUR_VENALE       NUMBER(19,2),
    VALEUR_NEUVE        NUMBER(19,2),
    CATEGORIE           NUMBER(10,0),
    SOUS_CATEGORIE      VARCHAR2(255),
    NUM_CHASSIS         VARCHAR2(255),
    CODE_CLIENT         VARCHAR2(255),
    NOM_CLIENT          VARCHAR2(255),
    NUM_CLIENT          VARCHAR2(255),
    TEL_CLIENT          VARCHAR2(255),
    ADRESSE_CLIENT      VARCHAR2(255),
    DATE_NAISSANCE      DATE,
    CIVILITE            VARCHAR2(255),
    CODE_PROFESSION     VARCHAR2(255),
    PROFESSION          VARCHAR2(255),
    SEXE                VARCHAR2(255),
    TYPE_PIECE          VARCHAR2(255),
    NUM_PIECE           VARCHAR2(255),
    SITUATION_MAT       VARCHAR2(255),
    NATIONALITE         VARCHAR2(255),
    RC                  NUMBER(19,2),
    DR                  NUMBER(19,2),
    BDG                 NUMBER(19,2),
    IPT                 NUMBER(19,2),
    INC                 NUMBER(19,2),
    VOL                 NUMBER(19,2),
    PRIME_NETTE         NUMBER(19,2),
    DROIT_TIMBRE        NUMBER(19,2),
    PRIME_TTC           NUMBER(19,2),
    ATTESTATION         VARCHAR2(255),
    CARTE_ROSE          VARCHAR2(255),
    CODE_ENERGIE        VARCHAR2(255),
    DTA                 NUMBER(19,2),
    DTC                 NUMBER(19,2),
    CONSTRAINT PK_POOLTPV_RISQUE PRIMARY KEY (ID)
);

-- ============================================
-- TABLE QUITTANCE_POOLTPV (ID = VARCHAR)
-- ============================================
CREATE TABLE POOLTPV_QUITTANCE (
    NUME_QUITTANCE      VARCHAR2(255) NOT NULL,
    NUME_POLICE         VARCHAR2(255),
    NUME_AVENANT        NUMBER(10,0),
    NATURE_MOUVEMENT    VARCHAR2(255),
    CODE_ASSURE         VARCHAR2(255),
    DATE_ENCAISSEMENT   TIMESTAMP,
    MODE_PAIEMENT       VARCHAR2(255),
    REF_ENCAISSEMENT    VARCHAR2(255),
    MONTANT_ENCAISSE    NUMBER(19,0),
    PRIME_TOTALE        NUMBER(19,0),
    STATUT              NUMBER(10,0),
    NUMERO_ENCAISSEMENT VARCHAR2(255),
    CONSTRAINT PK_POOLTPV_QUITTANCE PRIMARY KEY (NUME_QUITTANCE)
);
