CREATE SEQUENCE SEQ_INFOSADMINAGENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999999999999
    NOCYCLE
    NOCACHE
    NOORDER;

CREATE TABLE ZEN_INFOS_ADMIN_AGENCE
(
    ID              NUMBER(19)      NOT NULL,
    CODE_AGENCE     NUMBER(10),
    OFFICE_CODE     VARCHAR2(50)    NOT NULL,
    LIBELLE_AGENCE  VARCHAR2(255),
    USERNAME_ASAC   VARCHAR2(255)   NOT NULL UNIQUE,
    LOGIN           VARCHAR2(255),
    EMAIL           VARCHAR2(255),
    CLIENT_NAME     VARCHAR2(255),
    EXPIRES_AT      NUMBER(10)      DEFAULT 24 NOT NULL,
    CONSTRAINT PK_ZEN_INFOS_ADMIN_AGENCE PRIMARY KEY (ID)
);

COMMENT ON TABLE  ZEN_INFOS_ADMIN_AGENCE                        IS 'Informations administrateur agence Pool TPV';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.ID                     IS 'Identifiant unique (séquence SEQ_INFOSADMINAGENCE)';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.CODE_AGENCE            IS 'Code de l agence';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.OFFICE_CODE            IS 'Code ASAC (varchar)';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.LIBELLE_AGENCE         IS 'Libellé de l agence';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.LOGIN                  IS 'Login de l administrateur';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.EMAIL                  IS 'Email de l administrateur';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.USERNAME_ASAC          IS 'Username API ASAC unique';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.CLIENT_NAME            IS 'Nom du client';
COMMENT ON COLUMN ZEN_INFOS_ADMIN_AGENCE.EXPIRES_AT             IS 'Durée d expiration en heures (défaut 24)';

CREATE OR REPLACE TRIGGER TRG_ZEN_INFOS_ADMIN_AGENCE
    BEFORE INSERT ON ZEN_INFOS_ADMIN_AGENCE
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_INFOSADMINAGENCE.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/